name: CI - BarberShop

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: 📦 Construir el proyecto con Maven
        run: mvn clean package -DskipTests

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: 🧪 Ejecutar pruebas
        run: mvn test

      - name: 🧪 Ejecutar pruebas con cobertura
        run: mvn test jacoco:report

      - name: 📂 Guardar Reporte de JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
